{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-validate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/validate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/validate/validate_{{ version }}.tar.gz
  sha256: 04beca1ea6a733a7e113a5789aaa6c87778c8e0caa94aaae3927af4965f69974

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-settings
    - r-yaml
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-settings
    - r-yaml

test:
  commands:
    - $R -e "library('validate')"           # [not win]
    - "\"%R%\" -e \"library('validate')\""  # [win]

about:
  home: https://github.com/data-cleaning/validate
  license: GPL-3.0-only
  summary: Declare data validation rules and data quality indicators; confront data with them and analyze or visualize the results. The package supports rules that are per-field, in-record, cross-record or cross-dataset. Rules can be automatically analyzed for rule type and connectivity. See also Van der Loo and De Jonge
    (2018) <doi:10.1002/9781118897126>, chapter 6.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: validate
# Maintainer: Mark van der Loo <mark.vanderloo@gmail.com>
# License: GPL-3
# Title: Data Validation Infrastructure
# LazyData: no
# Type: Package
# LazyLoad: yes
# Authors@R: c(person("Mark", "van der Loo" , role   = c("cre","aut") , email  = "mark.vanderloo@gmail.com" , comment= c(ORCID="0000-0002-9807-4686")) , person("Edwin", "de Jonge" , role = "aut" ) , person("Paul","Hsieh" , role = "ctb" ))
# Description: Declare data validation rules and data quality indicators; confront data with them and analyze or visualize the results. The package supports rules that are per-field, in-record, cross-record or cross-dataset. Rules can be automatically analyzed for rule type and connectivity. See also Van der Loo and De Jonge (2018) <doi:10.1002/9781118897126>, chapter 6.
# Version: 0.9.2
# Depends: R (>= 3.1.3), methods
# URL: https://github.com/data-cleaning/validate
# BugReports: https://github.com/data-cleaning/validate/issues
# Imports: stats, graphics, settings, yaml
# Suggests: tinytest (>= 0.9.6), knitr, rmarkdown
# Enhances: lumberjack
# VignetteBuilder: knitr
# Collate: 'rule.R' 'sugar.R' 'validate_pkg.R' 'parse.R' 'expressionset.R' 'indicator.R' 'validator.R' 'confrontation.R' 'barplot.R' 'compare.R' 'factory.R' 'lumberjack.R' 'retailers.R' 'run_validation.R' 'syntax.R' 'utils.R' 'yaml.R'
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-08-26 08:38:31 UTC; mark
# Author: Mark van der Loo [cre, aut] (<https://orcid.org/0000-0002-9807-4686>), Edwin de Jonge [aut], Paul Hsieh [ctb]
# Repository: CRAN
# Date/Publication: 2019-08-28 11:40:08 UTC
