{% set version = '0.2.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-validate
  version: {{ version|replace("-", "_") }}

source:
  fn: validate_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/validate_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/validate/validate_{{ version }}.tar.gz
  sha256: e73af4cda05e7b787f95892a185f73bdca73cf4606d5d01b904e9037d894e635

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-settings
    - r-yaml

  run:
    - r-base
    - r-settings
    - r-yaml

test:
  commands:
    - $R -e "library('validate')"  # [not win]
    - "\"%R%\" -e \"library('validate')\""  # [win]

about:
  home: https://github.com/data-cleaning/validate
  license: GPL-3
  summary: Declare data validation rules and data quality indicators; confront data with them
    and analyze or visualize the results. The package supports rules that are per-field,
    in-record, cross-record or cross-dataset. Rules can be automatically analyzed for
    rule type and connectivity.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
