appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: wteynKEjI4U9uAc4y1eGP5q9fnK6V/5Efy3N1PjO9vJF78IqGWcf+e+/Gmn6+xEONSnzO3xiGN1kjpaP/BMVzxQ5zqNj4iD8qCBwW4nfaupoOE1GrNh6MxRvVRX4kb36bpRocX99QvIth/zuh6v+0685BCnAUkuBYJWykqVTzKfE75JSdgLiJQ58HzPT8jWJ2fX6MIjdhUKdfrtmhG0QhweXwNDvqxpGWmEqeJ3hJd3tOqjhxxftOe5W+/pSlNnDS1Qbb0B401eFWv6DBxloptTDN2WVeLIgSzzHjV4jItfFHcDbXGIRH1rNJXV17BLMRVq4EA4r01yLYLhPwcKm8bc3qxunIYMuI/eQMf8nx/qSBBm8oZYordnXIDKf/BvEyMbCkFep59OTiadQqVSUqAJl+6S1q7C57mcUIl/xyGrPSTew0f3eHop8szBijH6Qy2Jo/EHmOmNNfWVjNaw2RM8YbSWN/kq1epGPN+18hagORQsSsDMRwSLoPaTteeirUudV1JiHcyuR6yDXzZLWUvOt8gsMlwrPwa6s2r8Ai0u7poEeo/Rq2TijwFxaqOf6UdW1Lk7Jsszlc27lGZIZ3PckzmaN7mJZcUk1+FQClBD2DVONigq+FdpTyqjRFbMFgNLd+jAXJGx3Sb+dcsEDsI5dubv13NrTZUD4pbWbVn8=
conda_forge_output_validation: false
