travis:
  secure:
    BINSTAR_TOKEN: tGmuMaJRUzG0AVFlp5RJI4wPuu7BjN8U2jvEqlKumfccEsx1cHcI4UvctFG0NU6/Fbi90GAfSh0pyIJdpr+u1ZmsniP6sEfizni75M4dMwnKf44GqifcUc5WA4Gx4+RKh6/0nBZHyBSoX1vkUGhYNe8NmsTCktau/74cCCE/FWG+WmL2h+puq1uaYJedXaDC0Ug0MyR+UIdoiPAQCz/e6rPH5XZG2Eh9/A/W0J82fpu5Eye4+XXUZLy6q2lvt1YHSiv03NAzusBNnJP/ei5AKhatZFFPYNeMjegTnLFK9YSuVacvIu5+jiQkXTUH+B1sp5mn7Vu6gQpEY5Trp71NI92YA1pAcIgehlq9WCbCfiAx36euwXFm/ifF7efsX9H3lcwolrOp0yVetgUtZ/VwFUPVxuiYWwskvx4lnYLwpGU+Dy+CbZ0ZHcawD6NyFRaCpQ3U0onzAac3YgSG8TZhng3N5IJTcZC0TOdNVY/pXopAWcQcM6dtpUUc5pCEPMoQUO+mPJ32RYPugbk3kkucjB9AHO1FQxi8Y1x4EUd/HNosYuVISQgZ28Iwa1tSt1jHrIRa7oyW5L0GGADArwu0i1AKOAlIdnoI5uMZPaLBHMBykYoQKQE2eynkB2Q2uRiQ2ZqNza2C24L/fivDpBNbPVPmOEGRAoJNRUhmjj8rDrI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
